server:
  port: 3302
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
data:
  env: config-eureka-dev
  user:
    username: eureka-client-user
    password: 1291029102